Update standards in this module
TripalCultivate/TripalCultivate pull request #30
Opened 2024-11-06 00:40 UTC by laceysanderson

2024-11-06 23:05 UTC, carolyncaron requested changes
I haven't manually tested yet, but here's a few things that jumped out to me in the code!

2024-11-06 23:05 UTC, carolyncaron commented on .github/pull_request_template.md
> +*Please describe each things this PR does. For example, a PR may 1) solve a specific bug, 2) create an auomated test to ensure it doesn't return.*
```suggestion
*Please describe each things this PR does. For example, a PR may 1) solve a specific bug, 2) create an automated test to ensure it doesn't return.*
```

2024-11-06 23:05 UTC, carolyncaron commented on tests/src/Functional/ContentTypes/ContentTypeTest.php
> +        // Specifically, id, type, uid, title, status, created, changed, path).
```suggestion
        // This returns the 9 base fields too, so we add them to the list.
        // Specifically, id, type, uid, title, status, created, changed, path.
```

2024-11-06 23:05 UTC, carolyncaron commented on tests/src/Kernel/ImplementedHooksTest.php
> +  protected $connection;
```suggestion
  /**
   * A Database query interface for querying Chado using Tripal DBX.
   *
   * @var Drupal\tripal_chado\Database\ChadoConnection
   */
  protected ChadoConnection $chado_connection;
```

2024-11-06 23:05 UTC, carolyncaron commented on tests/src/Kernel/ImplementedHooksTest.php
> +    $this->connection = $this->getTestSchema(ChadoTestKernelBase::PREPARE_TEST_CHADO);
```suggestion
    $this->chado_connection = $this->getTestSchema(ChadoTestKernelBase::PREPARE_TEST_CHADO);
```

2024-11-06 23:05 UTC, carolyncaron commented on tests/src/Functional/ContentTypes/ContentTypeTest.php
I can't make a suggestion since it was an unaltered piece of code, but lines 30-34 contain the old $connection property

2024-11-07 16:20 UTC, laceysanderson commented on tests/src/Functional/ContentTypes/ContentTypeTest.php
Resolved in commit 75fed63a9c336327527db41e562cbf1982926124

2024-11-07 17:42 UTC, carolyncaron approved these changes
Manual test worked as expected. This looks great, thanks Lacey! 👍

2024-11-07 18:16 UTC, merged